# Get project details by project ID: group_name/project_name or project_id
@project_id=

GET {{gitlab.base_url}}/api/v4/projects/{{project_id}}/merge_requests
Content-Type: application/json
Authorization: Bearer {{gitlab.personal_access_token}}